name: Android Release (AAB)
on:
  workflow_dispatch:
    inputs:
      packageId: { description: "Android package id", required: false, default: "app.lovable.d2a8b5ffc2b3491dbcada0570b04c8b5" }
      versionName: { description: "Version name", required: false, default: "1.0.0" }
      versionCode: { description: "Version code", required: false, default: "1" }

jobs:
  build-aab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }
      - uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: npm ci || npm i

      - name: Build web app
        run: npm run build

      - name: Add Android platform (Capacitor)
        run: npx cap sync android

      - name: Set app version and package id
        working-directory: android
        run: |
          sed -i.bak 's/versionName "[^"]*"/versionName "${{ github.event.inputs.versionName }}"/' app/build.gradle || true
          sed -i.bak 's/versionCode [0-9]\+/versionCode ${{ github.event.inputs.versionCode }}/' app/build.gradle || true
          sed -i.bak 's/applicationId "[^"]*"/applicationId "${{ github.event.inputs.packageId }}"/' app/build.gradle || true

      - name: Build AAB
        working-directory: android
        run: |
          ./gradlew wrapper
          ./gradlew bundleRelease || ./gradlew bundleDebug

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-aab
          path: |
            android/app/build/outputs/bundle/release/*.aab
            android/app/build/outputs/bundle/debug/*.aab
